runtime: go
api_version: go1

handlers:
- url: /___fetch___
  script: _go_app
  login: admin
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /images
  static_dir: static/images
- url: /.*
  script: _go_app
